services:
  postgres:
    image: 'postgres:18'
    environment:
      - 'POSTGRES_DB=poker'
      - 'POSTGRES_PASSWORD=poker'
      - 'POSTGRES_USER=poker'
    ports:
      - '5432:5432'
    volumes:
      - poker-data:/var/lib/postgresql

volumes:
  poker-data:
